// 모든 사이트가 공유하는 설정. 배포 전 이 파일만 채우면 광고/분석/사이트 목록이 전체에 반영된다.
window.SITE_CONFIG = {
  // 원본은 example.com 자리표시자를 쓴다. 실제 주소는 deploy-prep.sh가 deploy.env 기준으로 dist/에서 치환한다.
  ROOT_DOMAIN: 'example.com',


  // GA4 측정 ID. 비어 있으면 스크립트를 아예 로드하지 않는다.
  GA4_ID: '', // 예: 'G-XXXXXXXXXX'
  // AdSense 앱 중간 광고 단위(melgene-mid, 반응형 디스플레이). 게시자 ID는 배포 때 <head>에 들어간다.
  AD_SLOT_MID: '5952905456',

  // 카카오톡 공유(ko 페이지). Kakao Developers 앱의 JavaScript 키 — 비어 있으면 휴대폰 공유 시트/링크 복사로 대신한다.
  KAKAO_JS_KEY: '',

  // Supabase (짧은 공유 링크·참여 수). 공개용 키만 넣는다: Project URL + publishable(anon) 키.
  // secret/service_role 키는 절대 넣지 않는다. 비어 있으면 해시 링크(#d=)로만 동작한다.
  SUPABASE_URL: '', // 배포 때 deploy-prep 이 deploy.local.env 값으로 채운다 (소스 저장소에는 두지 않음)
  SUPABASE_ANON_KEY: '', // 배포 때 채움 (publishable 키만)


  // 포털 & 크로스 프로모용 앱 목록 — 앱마다 apps/<id>/app.config.js 에 있고 아래 SITES 는 생성물이다.
  // title/desc 는 언어 코드별 객체(shared/i18n.js 의 LOCALES, 11개). 없는 언어는 en 으로 대체된다.
  // path 는 사이트 루트(en) 주소이고, 언어별 주소는 path + '<언어 dir>/' 로 자동 계산된다
  // (예: https://ladder.example.com/ja/). 특정 언어만 다른 주소를 쓰려면 paths: { ja: '...' } 로 덮어쓴다.
  // <sites:generated> apps/*/app.config.js 에서 node tools/gen-sites.js 가 만든다. 여기를 손으로 고치지 않는다.
  SITES: [
    {
      id: 'life',
      emoji: '🎞️',
      category: 'create',
      added: '2026-09-26',
      path: 'https://life.example.com/',
      title: { ko: '내 인생 애니메이션', en: 'My Life, Animated', ja: 'わたしの人生アニメ', zh: '我的人生动画', fr: 'Ma vie en animation', de: 'Mein Leben als Animation', th: 'แอนิเมชันชีวิตฉัน', vi: 'Cuộc đời tôi thành hoạt hình', es: 'Mi vida animada', it: 'Animazione della mia vita', pt: 'Animação da minha vida', ru: 'Анимация моей жизни' },
      desc: {
        ko: '태어난 날부터 오늘까지, 펜으로 그려지는 1분 인생 만화.',
        en: 'Your life from birth to today, drawn line by line in one minute.',
        ja: '生まれた日から今日まで、ペンで描く1分の人生マンガ。',
        zh: '从出生到今天，一分钟用画笔画出你的人生漫画。',
        fr: 'Votre vie, de la naissance à aujourd’hui, dessinée trait par trait en une minute.',
        de: 'Dein Leben von der Geburt bis heute – Strich für Strich in einer Minute gezeichnet.',
        th: 'ชีวิตคุณตั้งแต่เกิดจนถึงวันนี้ วาดทีละเส้นในหนึ่งนาที',
        vi: 'Cuộc đời bạn từ lúc chào đời đến hôm nay, vẽ từng nét trong một phút.',
        es: 'Tu vida desde que naciste hasta hoy, dibujada trazo a trazo en un minuto.',
        it: 'La tua vita dalla nascita a oggi, disegnata tratto dopo tratto in un minuto.',
        pt: 'Sua vida do nascimento até hoje, desenhada traço a traço em um minuto.',
        ru: 'Твоя жизнь от рождения до сегодня — линия за линией, за одну минуту.',
      },
    },
    {
      id: 'past-life',
      emoji: '🔮',
      category: 'test',
      added: '2026-09-26',
      path: 'https://past-life.example.com/',
      title: { ko: '나의 전생 테스트', en: 'Past Life Test', ja: '前世診断テスト', zh: '前世测试', fr: 'Test de vie antérieure', de: 'Früheres-Leben-Test', th: 'ทดสอบชาติที่แล้ว', vi: 'Trắc nghiệm kiếp trước', es: 'Test de vidas pasadas', it: 'Test vita precedente', pt: 'Teste de vida passada', ru: 'Кем я был в прошлой жизни' },
      desc: {
        ko: '12문항, 2분이면 끝. 당신은 전생에 누구였을까?',
        en: '12 questions, 2 minutes. Who were you in a past life?',
        ja: '12問・2分で完了。あなたの前世はだれだった？',
        zh: '12道题，2分钟搞定。你的前世是谁？',
        fr: '12 questions, 2 minutes. Qui étiez-vous dans une vie antérieure ?',
        de: '12 Fragen, 2 Minuten. Wer warst du in einem früheren Leben?',
        th: '12 ข้อ 2 นาทีจบ ชาติที่แล้วคุณเป็นใคร?',
        vi: '12 câu hỏi, 2 phút. Kiếp trước bạn là ai?',
        es: '12 preguntas, 2 minutos. ¿Quién fuiste en una vida pasada?',
        it: '12 domande, 2 minuti. Chi eri in una vita precedente?',
        pt: '12 perguntas, 2 minutos. Quem você foi em uma vida passada?',
        ru: '12 вопросов, 2 минуты — и ты узнаешь свою прошлую жизнь.',
      },
    },
    {
      id: 'ladder',
      emoji: '🪜',
      category: 'vote',
      added: '2026-09-26',
      path: 'https://ladder.example.com/',
      title: { ko: '사다리타기', en: 'Ladder Game', ja: 'あみだくじ', zh: '鬼脚图抽签', fr: 'Jeu de l’échelle', de: 'Leiterspiel', th: 'เกมบันไดสุ่ม', vi: 'Trò chơi bậc thang', es: 'Juego de la escalera', it: 'Gioco della scala', pt: 'Jogo da escada', ru: 'Жеребьёвка' },
      desc: {
        ko: '점심 메뉴부터 내기까지, 공정한 온라인 사다리타기.',
        en: 'Lunch picks, coffee runs, chores — a fair online random picker.',
        ja: 'ランチ決めからおごり決めまで。公平なオンラインあみだくじ。',
        zh: '从午餐吃什么到谁请客，公平的在线抽签。',
        fr: 'Déjeuner, qui paie le café, corvées — un tirage au sort équitable en ligne.',
        de: 'Mittagessen, wer zahlt den Kaffee, Aufgaben – faire Online-Auslosung.',
        th: 'ตั้งแต่เลือกเมนูมื้อเที่ยงถึงใครเลี้ยงกาแฟ สุ่มแบบยุติธรรมออนไลน์',
        vi: 'Từ chọn món trưa đến ai khao cà phê — bốc thăm trực tuyến công bằng.',
        es: 'Almuerzo, quién paga el café, tareas: un sorteo justo en línea.',
        it: 'Pranzo, chi paga il caffè, faccende: un sorteggio equo online.',
        pt: 'Almoço, quem paga o café, tarefas: um sorteio online justo.',
        ru: 'Обед, кто платит за кофе, дежурства — честная жеребьёвка онлайн.',
      },
    },
    {
      id: 'balance',
      emoji: '⚖️',
      category: 'test',
      added: '2026-09-27',
      path: 'https://balance.example.com/',
      title: { ko: '밸런스 게임', en: 'Would You Rather', ja: '究極の二択', zh: '二选一', fr: 'Tu préfères ?', de: 'Würdest du lieber?', th: 'จะเลือกอะไร?', vi: 'Bạn chọn bên nào?', es: '¿Qué prefieres?', it: 'Preferiresti?', pt: 'O que você prefere?', ru: 'Что бы ты выбрал?' },
      desc: {
        ko: '둘 중 하나만 고른다면? 다른 사람들은 몇 %가 골랐는지 바로 확인.',
        en: 'Pick one of two — then see what percent of everyone chose the same.',
        ja: 'どっちを選ぶ？ みんなの選択率がすぐわかる究極の二択。',
        zh: '只能选一个的话？马上看看大家的选择比例。',
        fr: 'Choisissez l’un des deux, puis voyez quel pourcentage a fait le même choix.',
        de: 'Wähle eins von zwei – und sieh, wie viel Prozent genauso gewählt haben.',
        th: 'ถ้าเลือกได้แค่ทางเดียว? ดูทันทีว่าคนอื่นเลือกกี่เปอร์เซ็นต์',
        vi: 'Chỉ được chọn một? Xem ngay bao nhiêu phần trăm mọi người chọn giống bạn.',
        es: 'Elige una de dos y mira qué porcentaje eligió lo mismo.',
        it: 'Scegli una delle due e scopri che percentuale ha fatto la tua stessa scelta.',
        pt: 'Escolha uma de duas opções e veja quantos por cento escolheram igual a você.',
        ru: 'Выбери одно из двух — и узнай, сколько процентов людей выбрали то же самое.',
      },
    },
    {
      id: 'reaction',
      emoji: '⚡',
      category: 'game',
      added: '2026-09-27',
      path: 'https://reaction.example.com/',
      title: { ko: '반응속도 테스트', en: 'Reaction Time Test', ja: '反応速度テスト', zh: '反应速度测试', fr: 'Test de réflexes', de: 'Reaktionstest', th: 'ทดสอบความไวในการตอบสนอง', vi: 'Kiểm tra tốc độ phản xạ', es: 'Test de reflejos', it: 'Test di reazione', pt: 'Teste de reação', ru: 'Тест на реакцию' },
      desc: {
        ko: '초록색이 되면 탭! 내 반응속도는 전체에서 상위 몇 %?',
        en: 'Tap when it turns green. How fast are you compared to everyone?',
        ja: '緑になったらタップ！ あなたの反応速度は上位何％？',
        zh: '变绿就点！你的反应速度排在前百分之几？',
        fr: 'Touchez quand ça devient vert. Êtes-vous plus rapide que les autres ?',
        de: 'Tippe, sobald es grün wird. Wie schnell bist du im Vergleich?',
        th: 'แตะเมื่อเป็นสีเขียว! ความไวของคุณอยู่ท็อปกี่เปอร์เซ็นต์?',
        vi: 'Chạm khi màn hình chuyển xanh! Bạn nhanh hơn bao nhiêu phần trăm người chơi?',
        es: 'Toca cuando se ponga verde. ¿Qué tan rápido eres comparado con todos?',
        it: 'Tocca quando diventa verde. Quanto sei veloce rispetto agli altri?',
        pt: 'Toque quando ficar verde. Você é mais rápido que os outros?',
        ru: 'Нажми, когда станет зелёным. Насколько ты быстрее остальных?',
      },
    },
    {
      id: 'roulette',
      emoji: '🎡',
      category: 'vote',
      added: '2026-09-27',
      path: 'https://roulette.example.com/',
      title: { ko: '돌림판', en: 'Spin the Wheel', ja: 'ルーレット', zh: '转盘抽签', fr: 'Roue de la fortune', de: 'Glücksrad', th: 'วงล้อสุ่ม', vi: 'Vòng quay may mắn', es: 'Ruleta', it: 'Ruota della fortuna', pt: 'Roleta aleatória', ru: 'Колесо фортуны' },
      desc: {
        ko: '점심 메뉴, 당번, 벌칙까지. 항목만 적고 돌리면 끝.',
        en: 'Lunch, chores, dares — type your options and spin.',
        ja: 'ランチも当番も罰ゲームも。項目を書いて回すだけ。',
        zh: '午餐、值日、惩罚游戏，写好选项转一转就行。',
        fr: 'Déjeuner, corvées, gages — écrivez vos options et faites tourner.',
        de: 'Mittagessen, Aufgaben, Mutproben – Optionen eintragen und drehen.',
        th: 'มื้อเที่ยง เวร บทลงโทษ เขียนตัวเลือกแล้วหมุนเลย',
        vi: 'Món trưa, trực nhật, hình phạt — nhập lựa chọn rồi quay.',
        es: 'Almuerzo, tareas, retos: escribe tus opciones y gira.',
        it: 'Pranzo, turni, penitenze: scrivi le opzioni e gira.',
        pt: 'Almoço, tarefas, desafios: escreva as opções e gire.',
        ru: 'Обед, дежурства, фанты — впиши варианты и крути.',
      },
    },
    {
      id: 'monster',
      emoji: '🎃',
      category: 'test',
      added: '2026-09-27',
      path: 'https://monster.example.com/',
      title: { ko: '할로윈 몬스터 테스트', en: 'Which Monster Are You?', ja: 'モンスター診断', zh: '万圣节怪物测试', fr: 'Quel monstre es-tu ?', de: 'Welches Monster bist du?', th: 'คุณคือปีศาจฮาโลวีนตัวไหน?', vi: 'Bạn là quái vật nào?', es: '¿Qué monstruo eres?', it: 'Che mostro sei?', pt: 'Que monstro você é?', ru: 'Какой ты монстр?' },
      desc: {
        ko: '할로윈 밤 10문항, 1분이면 끝. 나를 닮은 몬스터는 누구?',
        en: '10 spooky-cute questions for Halloween night. Which monster is your twin?',
        ja: 'ハロウィンの夜の10問で診断。あなたにそっくりなモンスターは？',
        zh: '万圣节之夜10道题，1分钟测出和你最像的怪物。',
        fr: '10 questions mignonnes et un brin effrayantes pour Halloween. Quel monstre te ressemble ?',
        de: '10 schaurig-süße Fragen zur Halloween-Nacht. Welches Monster passt zu dir?',
        th: '10 คำถามคืนฮาโลวีน 1 นาทีรู้ผล ปีศาจตัวไหนเหมือนคุณที่สุด?',
        vi: '10 câu hỏi đêm Halloween, 1 phút có kết quả. Quái vật nào giống bạn nhất?',
        es: '10 preguntas tiernamente terroríficas para Halloween. ¿Qué monstruo se parece a ti?',
        it: '10 domande tra brividi e tenerezza per la notte di Halloween. Quale mostro ti somiglia?',
        pt: '10 perguntas fofas e assustadoras para a noite de Halloween. Qual monstro combina com você?',
        ru: 'Тест на Хэллоуин: 10 жутко милых вопросов за минуту. Какой монстр — твой двойник?',
      },
    },
    {
      id: 'pumpkin',
      emoji: '🎃',
      category: 'create',
      added: '2026-09-28',
      path: 'https://pumpkin.example.com/',
      title: { ko: '할로윈 호박 꾸미기', en: 'Pumpkin Carving Online', ja: 'かぼちゃランタン作り', zh: '万圣节南瓜灯制作', fr: 'Sculpter une citrouille', de: 'Kürbis schnitzen online', th: 'แกะสลักฟักทองฮาโลวีน', vi: 'Khắc bí ngô Halloween', es: 'Tallar calabaza de Halloween', it: 'Intagliare la zucca di Halloween', pt: 'Esculpir abóbora de Halloween', ru: 'Вырезать тыкву на Хэллоуин' },
      desc: {
        ko: '눈·코·입을 골라 나만의 잭오랜턴을 만들고 촛불을 켜 보세요. 이미지로 저장하고 친구에게 보내기.',
        en: 'Pick eyes, nose and mouth, light the candle and carve your own jack-o’-lantern. Save it as an image or send it to a friend.',
        ja: '目・鼻・口を選んで自分だけのジャックオーランタンを作ろう。ろうそくを灯して画像保存、友だちにも送れる。',
        zh: '挑选眼睛、鼻子和嘴巴，点亮蜡烛，做一盏专属南瓜灯。可以存成图片，也能发给朋友。',
        fr: 'Choisis les yeux, le nez et la bouche, allume la bougie et crée ta citrouille d’Halloween. Enregistre l’image ou envoie-la à un ami.',
        de: 'Augen, Nase und Mund aussuchen, Kerze anzünden und deinen eigenen Halloween-Kürbis schnitzen. Als Bild speichern oder Freunden schicken.',
        th: 'เลือกตา จมูก ปาก จุดเทียน แล้วสร้างฟักทองแจ็คโอแลนเทิร์นของคุณเอง บันทึกเป็นรูปหรือส่งให้เพื่อนได้',
        vi: 'Chọn mắt, mũi, miệng, thắp nến và khắc chiếc đèn bí ngô của riêng bạn. Lưu thành ảnh hoặc gửi cho bạn bè.',
        es: 'Elige ojos, nariz y boca, enciende la vela y talla tu propia calabaza de Halloween. Guárdala como imagen o envíasela a un amigo.',
        it: 'Scegli occhi, naso e bocca, accendi la candela e intaglia la tua zucca di Halloween. Salvala come immagine o mandala a un amico.',
        pt: 'Escolha olhos, nariz e boca, acenda a vela e esculpa sua própria abóbora de Halloween. Salve como imagem ou mande para um amigo.',
        ru: 'Выбери глаза, нос и рот, зажги свечу и вырежи свою тыкву-фонарь. Сохрани картинку или отправь другу.',
      },
    },
    {
      id: 'food-cup',
      emoji: '🍽️',
      category: 'vote',
      added: '2026-09-29',
      path: 'https://food-cup.example.com/',
      title: { ko: '음식 월드컵', en: 'Food Tournament', ja: '食べ物トーナメント', zh: '美食世界杯', fr: 'Tournoi de bouffe', de: 'Essen-Turnier', th: 'ทัวร์นาเมนต์อาหาร', vi: 'Giải đấu món ăn', es: 'Torneo de comida', it: 'Torneo del cibo', pt: 'Torneio de comida', ru: 'Битва блюд' },
      desc: {
        ko: '두 음식 중 더 먹고 싶은 걸 골라 16강부터 결승까지. 끝까지 남는 내 최애 음식과 다른 사람들의 실제 선택률을 확인해요.',
        en: 'Two dishes at a time: tap the one you’d rather eat, from the round of 16 to the final, and see how others really picked.',
        ja: '2つの料理から食べたい方を選んで1回戦から決勝まで。最後に残る好きな食べ物と、みんなの本当の選択率がわかる。',
        zh: '两道菜选一道更想吃的，从16强一路选到决赛，看看你的本命美食和大家的真实选择比例。',
        fr: 'Deux plats à chaque duel : touche celui que tu préfères manger, des huitièmes à la finale, et vois ce que les autres ont vraiment choisi.',
        de: 'Immer zwei Gerichte: Tippe auf das, was du lieber isst – vom Achtelfinale bis zum Finale – und sieh, was andere wirklich gewählt haben.',
        th: 'เลือกเมนูที่อยากกินมากกว่าทีละสองจาน ตั้งแต่รอบ 16 ทีมจนถึงรอบชิง แล้วดูว่าคนอื่นเลือกอะไรจริง ๆ',
        vi: 'Mỗi lượt hai món: chạm vào món bạn muốn ăn hơn, từ vòng 1/8 đến chung kết, rồi xem mọi người thật sự đã chọn gì.',
        es: 'Dos platos por duelo: toca el que prefieres comer, de octavos a la final, y mira qué eligieron de verdad los demás.',
        it: 'Due piatti per sfida: tocca quello che preferisci mangiare, dagli ottavi alla finale, e scopri cosa hanno scelto davvero gli altri.',
        pt: 'Dois pratos por disputa: toque no que você prefere comer, das oitavas à final, e veja o que os outros escolheram de verdade.',
        ru: 'Каждый раз два блюда: выбирай, что съел бы с большей охотой, от 1/8 до финала, и смотри, что на самом деле выбрали другие.',
      },
    },
    {
      id: 'candy-catch',
      emoji: '🍬',
      category: 'game',
      added: '2026-09-30',
      path: 'https://candy-catch.example.com/',
      title: { ko: '할로윈 사탕 받기 게임', en: 'Halloween Candy Catch', ja: 'ハロウィン お菓子キャッチ', zh: '万圣节接糖果', fr: 'Attrape-bonbons', de: 'Halloween-Süßigkeiten fangen', th: 'เกมรับขนมฮาโลวีน', vi: 'Hứng kẹo Halloween', es: 'Atrapa dulces de Halloween', it: 'Acchiappa caramelle', pt: 'Pegar doces de Halloween', ru: 'Лови конфеты на Хэллоуин' },
      desc: {
        ko: '하늘에서 쏟아지는 사탕을 호박 바구니로 받아요. 거미와 유령은 피하고 콤보로 점수를 올리는 50초 아케이드 게임.',
        en: 'Candy is raining down: slide your pumpkin bucket to catch it, dodge spiders and ghosts, and build combos in 50 seconds.',
        ja: '空から降ってくるお菓子をかぼちゃバケツでキャッチ。クモとおばけをよけて、コンボでスコアを伸ばす50秒ゲーム。',
        zh: '糖果从天而降，左右移动南瓜桶接住它们，躲开蜘蛛和幽灵，用连击刷高分。一局50秒。',
        fr: 'Les bonbons tombent du ciel : glisse ton seau citrouille pour les attraper, évite araignées et fantômes et enchaîne les combos en 50 s.',
        de: 'Süßigkeiten regnen vom Himmel: Schieb deinen Kürbiseimer hin und her, weich Spinnen und Geistern aus und sammle Combos – 50 Sekunden.',
        th: 'ขนมร่วงลงมาจากฟ้า เลื่อนถังฟักทองไปรับ หลบแมงมุมกับผี แล้วทำคอมโบเก็บแต้มใน 50 วินาที',
        vi: 'Kẹo rơi từ trên trời: kéo xô bí ngô để hứng, né nhện và ma, nối combo để ghi điểm trong 50 giây.',
        es: 'Llueven dulces del cielo: mueve tu cubeta de calabaza para atraparlos, esquiva arañas y fantasmas y haz combos en 50 segundos.',
        it: 'Piovono caramelle dal cielo: sposta il secchiello a zucca per prenderle, schiva ragni e fantasmi e fai combo in 50 secondi.',
        pt: 'Chovem doces do céu: mova seu balde de abóbora para pegar, desvie de aranhas e fantasmas e faça combos em 50 segundos.',
        ru: 'С неба сыплются конфеты: двигай ведёрко-тыкву, лови сладости, уворачивайся от пауков и призраков и собирай комбо за 50 секунд.',
      },
    },
    {
      id: 'aura',
      emoji: '🔮',
      category: 'test',
      added: '2026-09-30',
      path: 'https://aura.example.com/',
      title: { ko: '오라 컬러 테스트', en: 'Aura Color Test', ja: 'オーラ診断', zh: '气场颜色测试', fr: 'Test couleur d’aura', de: 'Aura-Farben-Test', th: 'ทดสอบสีออร่า', vi: 'Test màu aura', es: 'Test de aura', it: 'Test dell’aura', pt: 'Teste da aura', ru: 'Тест на цвет ауры' },
      desc: {
        ko: '일상 속 12가지 순간으로 알아보는 나의 오라 색깔. 2분이면 끝나요.',
        en: '12 everyday moments, about 2 minutes. What color is the glow your energy gives off?',
        ja: '日常の12のシーンで、あなたのオーラカラーを診断。約2分でわかります。',
        zh: '12个日常小场景，2分钟测出你的气场是什么颜色。',
        fr: '12 petits moments du quotidien, environ 2 minutes. De quelle couleur est ton aura ?',
        de: '12 Alltagsmomente, etwa 2 Minuten. Welche Farbe hat deine Aura?',
        th: '12 สถานการณ์ในชีวิตประจำวัน 2 นาทีรู้ผล ออร่าของคุณสีอะไร?',
        vi: '12 khoảnh khắc thường ngày, khoảng 2 phút. Hào quang của bạn có màu gì?',
        es: '12 momentos del día a día, unos 2 minutos. ¿De qué color es tu aura?',
        it: '12 momenti di tutti i giorni, circa 2 minuti. Di che colore è la tua aura?',
        pt: '12 momentos do dia a dia, uns 2 minutos. Qual é a cor da sua aura?',
        ru: '12 житейских ситуаций, пара минут. Какого цвета твоя аура?',
      },
    },
    {
      id: 'ghost',
      emoji: '👻',
      category: 'create',
      added: '2026-10-01',
      path: 'https://ghost.example.com/',
      title: { ko: '나만의 유령 만들기', en: 'Ghost Maker', ja: 'おばけメーカー', zh: '万圣节小幽灵制作', fr: 'Créer son fantôme', de: 'Gespenst erstellen', th: 'สร้างผีน้อยฮาโลวีน', vi: 'Tạo con ma Halloween', es: 'Crea tu fantasma', it: 'Crea il tuo fantasmino', pt: 'Crie seu fantasminha', ru: 'Создай привидение' },
      desc: {
        ko: '몸 모양·눈·입·모자를 골라 둥실둥실 떠다니는 나만의 귀여운 유령을 만들어 보세요. 이미지로 저장하고 친구에게 보내기.',
        en: 'Pick a body, eyes, mouth and a hat and make your own cute floating ghost. Save it as an image or send it to a friend.',
        ja: 'からだ・目・口・帽子を選んで、ふわふわ浮かぶ自分だけのおばけを作ろう。画像保存も、友だちに送るのもOK。',
        zh: '挑选身体、眼睛、嘴巴和帽子，捏一只轻飘飘的专属小幽灵。可以存成图片，也能发给朋友。',
        fr: 'Choisis la forme, les yeux, la bouche et un chapeau pour créer ton petit fantôme qui flotte. Enregistre l’image ou envoie-la à un ami.',
        de: 'Form, Augen, Mund und Hut aussuchen und dein eigenes süßes Schwebe-Gespenst gestalten. Als Bild speichern oder Freunden schicken.',
        th: 'เลือกรูปร่าง ตา ปาก และหมวก สร้างผีน้อยน่ารักที่ลอยไปมาของคุณเอง บันทึกเป็นรูปหรือส่งให้เพื่อนได้',
        vi: 'Chọn dáng, mắt, miệng và mũ để tạo chú ma nhỏ dễ thương bay lơ lửng của riêng bạn. Lưu thành ảnh hoặc gửi cho bạn bè.',
        es: 'Elige forma, ojos, boca y sombrero y crea tu propio fantasmita tierno que flota. Guárdalo como imagen o mándaselo a un amigo.',
        it: 'Scegli forma, occhi, bocca e cappello e crea il tuo fantasmino tenerissimo che fluttua. Salvalo come immagine o mandalo a un amico.',
        pt: 'Escolha formato, olhos, boca e chapéu e crie seu fantasminha fofo que flutua. Salve como imagem ou mande para um amigo.',
        ru: 'Выбери форму, глаза, рот и шляпу и создай своё милое парящее привидение. Сохрани картинку или отправь другу.',
      },
    },
    {
      id: 'team',
      emoji: '🎲',
      category: 'vote',
      added: '2026-10-01',
      path: 'https://team.example.com/',
      title: { ko: '랜덤 팀 나누기', en: 'Random Team Generator', ja: 'チーム分け', zh: '随机分组', fr: 'Générateur d’équipes', de: 'Zufällige Teams', th: 'สุ่มแบ่งทีม', vi: 'Chia đội ngẫu nhiên', es: 'Generador de equipos', it: 'Generatore di squadre', pt: 'Sorteador de times', ru: 'Разделить на команды' },
      desc: {
        ko: '이름만 붙여 넣으면 팀 수나 팀당 인원대로 공정하게 조 편성. 주장은 서로 다른 팀으로, 결과는 링크로 그대로 공유.',
        en: 'Paste names, pick teams or people per team, and shuffle into fair teams. Captains apart, same result in a share link.',
        ja: '名前を貼るだけで、チーム数か人数で公平にチーム分け。リーダーは別々のチームに、結果はリンクでそのまま共有。',
        zh: '粘贴名单，按组数或每组人数公平随机分组。组长分到不同组，结果用链接原样分享。',
        fr: 'Colle les prénoms, choisis le nombre d’équipes ou de joueurs par équipe et mélange. Capitaines séparés, résultat partageable.',
        de: 'Namen einfügen, Anzahl der Teams oder Personen pro Team wählen, mischen. Kapitäne getrennt, Ergebnis per Link teilen.',
        th: 'วางรายชื่อแล้วสุ่มแบ่งทีมอย่างยุติธรรมตามจำนวนทีมหรือจำนวนคนต่อทีม หัวหน้าแยกคนละทีม แชร์ผลเดิมด้วยลิงก์',
        vi: 'Dán danh sách tên, chọn số đội hoặc số người mỗi đội rồi chia ngẫu nhiên công bằng. Đội trưởng tách riêng, chia sẻ bằng link.',
        es: 'Pega los nombres, elige cuántos equipos o personas por equipo y mezcla. Capitanes separados, mismo resultado en un enlace.',
        it: 'Incolla i nomi, scegli quante squadre o persone per squadra e mescola. Capitani separati, stesso risultato in un link.',
        pt: 'Cole os nomes, escolha quantos times ou pessoas por time e sorteie. Capitães separados, mesmo resultado num link.',
        ru: 'Вставь имена, выбери число команд или людей в команде — и перемешай. Капитаны порознь, результат по ссылке.',
      },
    },
    {
      id: 'merge',
      emoji: '🎃',
      category: 'game',
      added: '2026-10-02',
      path: 'https://merge.example.com/',
      title: { ko: '할로윈 수박게임', en: 'Suika Game Halloween', ja: 'スイカゲーム ハロウィン', zh: '合成大西瓜 万圣节版', fr: 'Jeu de la pastèque – Halloween', de: 'Suika Game Halloween', th: 'เกมแตงโม ฮาโลวีน', vi: 'Game dưa hấu Halloween', es: 'Juego de la sandía – Halloween', it: 'Gioco dell’anguria', pt: 'Jogo da melancia – Halloween', ru: 'Арбузная игра на Хэллоуин' },
      desc: {
        ko: '사탕을 병에 떨어뜨려 같은 것끼리 합치면 더 큰 것으로! 선을 넘기지 않고 거대 잭오랜턴까지 키워 보는 할로윈 수박 게임.',
        en: 'Drop treats into the jar and merge matching pairs into bigger ones. Keep the pile under the line and grow a giant jack-o’-lantern.',
        ja: 'お菓子をビンに落として、同じもの同士をくっつけると大きく進化。線を越えないように巨大ジャック・オー・ランタンを目指そう。',
        zh: '把糖果丢进罐子，两个一样的碰在一起就合成更大的！别让它们越过红线，一路合成巨型南瓜灯。',
        fr: 'Lâche des friandises dans le bocal et fusionne les paires identiques. Reste sous la ligne et fais grandir une citrouille géante.',
        de: 'Lass Süßes ins Glas fallen und verschmelze gleiche Paare zu größeren. Bleib unter der Linie und züchte die Riesen-Kürbislaterne.',
        th: 'ปล่อยขนมลงขวดโหล ของเหมือนกันชนกันจะรวมร่างเป็นชิ้นใหญ่ขึ้น อย่าให้ล้นเส้น แล้วไปให้ถึงฟักทองยักษ์',
        vi: 'Thả kẹo vào hũ, hai món giống nhau chạm vào sẽ gộp thành món lớn hơn. Đừng để tràn vạch và nuôi đèn bí ngô khổng lồ.',
        es: 'Suelta dulces en el frasco y fusiona las parejas iguales en algo más grande. No pases la línea y llega a la calabaza gigante.',
        it: 'Lascia cadere i dolcetti nel barattolo e unisci le coppie uguali. Resta sotto la linea e fai crescere la zucca gigante.',
        pt: 'Solte doces no pote e junte os pares iguais em algo maior. Não passe da linha e chegue à abóbora gigante.',
        ru: 'Бросай сладости в банку и соединяй одинаковые в более крупные. Не переходи черту и вырасти гигантский фонарь Джека.',
      },
    },
    {
      id: 'costume',
      emoji: '🎭',
      category: 'test',
      added: '2026-10-02',
      path: 'https://costume.example.com/',
      title: { ko: '할로윈 코스튬 추천', en: 'Halloween Costume Quiz', ja: 'ハロウィン仮装診断', zh: '万圣节装扮测试', fr: 'Quiz déguisement', de: 'Halloween-Kostüm-Test', th: 'ทดสอบชุดฮาโลวีน', vi: 'Test hóa trang Halloween', es: 'Test de disfraz de Halloween', it: 'Test costume di Halloween', pt: 'Teste de fantasia de Halloween', ru: 'Тест: какой костюм на Хэллоуин' },
      desc: {
        ko: '파티 속 12가지 순간으로 찾는 올해 나의 할로윈 코스튬. 만드는 팁까지 2분이면 끝!',
        en: '12 party moments, about 2 minutes. Find the Halloween costume that fits your personality — with easy DIY tips.',
        ja: 'パーティーの12シーンで、今年のあなたにぴったりの仮装を診断。手作りのコツ付き、約2分。',
        zh: '12个派对小场景，2分钟测出今年最适合你的万圣节装扮，附简单DIY小贴士。',
        fr: '12 moments de soirée, environ 2 minutes. Trouve le déguisement d’Halloween qui colle à ta personnalité, astuces DIY en prime.',
        de: '12 Partymomente, etwa 2 Minuten. Finde das Halloween-Kostüm, das zu deiner Persönlichkeit passt – mit DIY-Tipps.',
        th: '12 สถานการณ์ในปาร์ตี้ 2 นาทีรู้ผล ปีนี้ชุดฮาโลวีนแบบไหนเข้ากับนิสัยคุณที่สุด พร้อมทริคทำเอง',
        vi: '12 khoảnh khắc trong bữa tiệc, khoảng 2 phút. Tìm bộ hóa trang Halloween hợp tính cách bạn, kèm mẹo tự làm.',
        es: '12 momentos de fiesta, unos 2 minutos. Descubre el disfraz de Halloween que va con tu personalidad, con trucos para hacerlo tú.',
        it: '12 momenti di festa, circa 2 minuti. Scopri il costume di Halloween adatto alla tua personalità, con consigli fai-da-te.',
        pt: '12 momentos de festa, uns 2 minutos. Descubra a fantasia de Halloween que combina com você, com dicas para fazer em casa.',
        ru: '12 моментов с вечеринки, пара минут. Узнай, какой костюм на Хэллоуин подходит твоему характеру, — с идеями, как сделать его самому.',
      },
    },
    {
      id: 'invite',
      emoji: '💌',
      category: 'create',
      added: '2026-10-03',
      path: 'https://invite.example.com/',
      title: { ko: '할로윈 파티 초대장', en: 'Party Invitation Maker', ja: 'ハロウィン招待状メーカー', zh: '万圣节派对邀请函制作', fr: 'Invitation Halloween', de: 'Halloween-Einladung', th: 'สร้างการ์ดเชิญปาร์ตี้ฮาโลวีน', vi: 'Tạo thiệp mời tiệc Halloween', es: 'Invitación de fiesta de Halloween', it: 'Invito per festa di Halloween', pt: 'Convite de festa de Halloween', ru: 'Приглашение на Хэллоуин' },
      desc: {
        ko: '파티 이름·날짜·시간·장소·한마디를 넣고 유령·호박·박쥐·마녀 테마를 골라 오싹한 초대장을 만들어 보세요. 이미지 저장, 링크 공유, 텍스트 복사.',
        en: 'Add the party name, date, time, place and a note, pick a ghost, pumpkin, bat or witch theme and make a spooky invitation. Save the image, share a link or copy the text.',
        ja: 'パーティー名・日時・場所・ひとことを入れて、おばけ・かぼちゃ・コウモリ・魔女のテーマで招待状を作ろう。画像保存、リンク共有、テキストコピーもOK。',
        zh: '填写派对名称、日期、时间、地点和留言，选择幽灵、南瓜、蝙蝠或女巫主题，做一张惊悚邀请函。可存图片、分享链接或复制文字。',
        fr: 'Ajoute le nom de la fête, la date, l’heure, le lieu et un mot, choisis un thème fantôme, citrouille, chauve-souris ou sorcière. Enregistre l’image, partage le lien ou copie le texte.',
        de: 'Partyname, Datum, Uhrzeit, Ort und eine Nachricht eintragen, Gespenst-, Kürbis-, Fledermaus- oder Hexen-Motiv wählen. Als Bild speichern, Link teilen oder Text kopieren.',
        th: 'ใส่ชื่องาน วันที่ เวลา สถานที่ และข้อความ เลือกธีมผี ฟักทอง ค้างคาว หรือแม่มด บันทึกเป็นรูป แชร์ลิงก์ หรือคัดลอกข้อความได้',
        vi: 'Nhập tên tiệc, ngày, giờ, địa điểm và lời nhắn, chọn chủ đề ma, bí ngô, dơi hoặc phù thủy. Lưu thành ảnh, chia sẻ link hoặc sao chép nội dung.',
        es: 'Escribe el nombre de la fiesta, la fecha, la hora, el lugar y un mensaje, y elige un tema de fantasma, calabaza, murciélago o bruja. Guarda la imagen, comparte el enlace o copia el texto.',
        it: 'Scrivi nome della festa, data, ora, luogo e un messaggio, scegli un tema fantasma, zucca, pipistrello o strega. Salva l’immagine, condividi il link o copia il testo.',
        pt: 'Escreva o nome da festa, a data, a hora, o local e um recado, e escolha um tema de fantasma, abóbora, morcego ou bruxa. Salve a imagem, compartilhe o link ou copie o texto.',
        ru: 'Впиши название вечеринки, дату, время, место и пару слов, выбери тему — привидение, тыква, летучая мышь или ведьма. Сохрани картинку, поделись ссылкой или скопируй текст.',
      },
    },
    {
      id: 'lunch',
      emoji: '🍽️',
      category: 'vote',
      added: '2026-10-03',
      path: 'https://lunch.example.com/',
      title: { ko: '오늘 뭐 먹지', en: 'What Should I Eat?', ja: '今日のご飯 何食べる', zh: '今天吃什么', fr: 'On mange quoi ?', de: 'Was esse ich heute?', th: 'วันนี้กินอะไรดี', vi: 'Hôm nay ăn gì', es: '¿Qué como hoy?', it: 'Cosa mangio oggi?', pt: 'O que comer hoje?', ru: 'Что съесть сегодня?' },
      desc: {
        ko: '아침·점심·저녁·야식과 기분만 고르고 슬롯머신 릴을 돌려 메뉴를 뽑아요. 마음에 안 드는 메뉴는 제외하고 다시 뽑기.',
        en: 'Pick a meal and a mood, spin the slot-machine reels and get a dish to eat. Skip what you don’t like and spin again.',
        ja: '朝・昼・夜・夜食と気分を選んでスロットを回すだけ。食べたくないメニューは除外して、もう一度回せます。',
        zh: '选好早餐、午餐、晚餐或宵夜和心情，转动老虎机就能抽到今天吃什么。不想吃的可以排除后重抽。',
        fr: 'Choisis le repas et l’humeur, fais tourner les rouleaux et découvre quoi manger. Écarte un plat et relance.',
        de: 'Mahlzeit und Stimmung wählen, die Walzen drehen und ein Gericht bekommen. Unliebsames überspringen und neu drehen.',
        th: 'เลือกมื้อและอารมณ์ แล้วหมุนสล็อตเพื่อสุ่มเมนูอาหาร ไม่อยากกินอะไรก็ตัดออกแล้วหมุนใหม่ได้',
        vi: 'Chọn bữa và tâm trạng rồi quay cuộn máy xèng để ra món ăn. Món không thích thì loại ra và quay lại.',
        es: 'Elige la comida y el ánimo, gira los rodillos y descubre qué comer. Descarta lo que no te apetece y vuelve a girar.',
        it: 'Scegli il pasto e l’umore, fai girare i rulli e scopri cosa mangiare. Escludi ciò che non ti va e rigira.',
        pt: 'Escolha a refeição e o humor, gire os rolos e descubra o que comer. Tire o que não quer e gire de novo.',
        ru: 'Выбери приём пищи и настроение, крути барабаны и узнай, что съесть. Не нравится блюдо — убери и крути снова.',
      },
    },
    {
      id: 'game2048',
      emoji: '🔢',
      category: 'game',
      added: '2026-10-04',
      path: 'https://game2048.example.com/',
      title: { ko: '2048 게임', en: '2048 Game', ja: '2048 ゲーム', zh: '2048 小游戏', fr: 'Jeu 2048', de: '2048 Spiel', th: 'เกม 2048', vi: 'Game 2048', es: 'Juego 2048', it: 'Gioco 2048', pt: 'Jogo 2048', ru: 'Игра 2048' },
      desc: {
        ko: '밀어서 같은 숫자끼리 합치고 2048까지! 스와이프·방향키로 하는 할로윈판 숫자 퍼즐.',
        en: 'Slide the tiles, merge matching numbers and reach 2048. The classic number puzzle with a Halloween twist — swipe or use arrow keys.',
        ja: 'スライドして同じ数字を合体、2048を目指そう。スワイプでも矢印キーでも遊べるハロウィン版の数字パズル。',
        zh: '滑动方块，合并相同数字，一路合成2048！支持滑动和方向键的万圣节版数字益智游戏。',
        fr: 'Fais glisser les tuiles, fusionne les nombres identiques et atteins 2048. Le casse-tête culte, version Halloween.',
        de: 'Kacheln schieben, gleiche Zahlen verschmelzen und die 2048 knacken. Das Zahlenrätsel-Kultspiel als Halloween-Edition.',
        th: 'ปัดแผ่นตัวเลข รวมเลขเดียวกัน แล้วไปให้ถึง 2048 เกมตัวเลขสุดคลาสสิกฉบับฮาโลวีน เล่นด้วยการปัดหรือปุ่มลูกศร',
        vi: 'Trượt các ô, ghép những số giống nhau và đạt tới 2048. Trò xếp số kinh điển phiên bản Halloween.',
        es: 'Desliza las fichas, fusiona los números iguales y llega al 2048. El puzle clásico con un toque de Halloween.',
        it: 'Fai scorrere le tessere, unisci i numeri uguali e arriva a 2048. Il rompicapo classico in versione Halloween.',
        pt: 'Deslize as peças, junte os números iguais e chegue ao 2048. O quebra-cabeça clássico com clima de Halloween.',
        ru: 'Сдвигай плитки, соединяй одинаковые числа и дойди до 2048. Классическая головоломка в хэллоуинском стиле.',
      },
    },
    {
      id: 'lovestyle',
      emoji: '💘',
      category: 'test',
      added: '2026-10-04',
      path: 'https://lovestyle.example.com/',
      title: { ko: '연애 유형 테스트', en: 'Love Style Test', ja: '恋愛タイプ診断', zh: '恋爱类型测试', fr: 'Test amoureux', de: 'Liebestyp-Test', th: 'ทดสอบสไตล์ความรัก', vi: 'Trắc nghiệm tình yêu', es: 'Test del amor', it: 'Test dell’amore', pt: 'Teste do amor', ru: 'Тест на тип любви' },
      desc: {
        ko: '썸부터 데이트, 사소한 다툼까지 10가지 순간으로 알아보는 나의 연애 스타일. 2~3분이면 끝나요.',
        en: '10 little dating moments, 2–3 minutes. Discover what kind of partner you really are, plus your best match.',
        ja: '片思いからデート、ちょっとしたケンカまで。10の場面で分かるあなたの恋愛タイプ。約2〜3分。',
        zh: '从暧昧到约会再到小争吵，10个恋爱小场景，2~3分钟测出你是哪种恋人。',
        fr: '10 petits moments amoureux, 2 à 3 minutes. Découvre quel genre de partenaire tu es vraiment, et ton match idéal.',
        de: '10 kleine Dating-Momente, 2–3 Minuten. Finde heraus, welcher Liebestyp du wirklich bist – und wer am besten zu dir passt.',
        th: '10 สถานการณ์ความรักเล็ก ๆ ใช้เวลา 2–3 นาที รู้เลยว่าเวลามีความรักคุณเป็นแฟนแบบไหน พร้อมคู่ที่เข้ากันที่สุด',
        vi: '10 khoảnh khắc hẹn hò nhỏ, 2–3 phút. Khám phá kiểu người yêu thật sự của bạn và người hợp với bạn nhất.',
        es: '10 momentos de pareja, 2 o 3 minutos. Descubre qué tipo de pareja eres de verdad y con quién haces match.',
        it: '10 piccoli momenti di coppia, 2-3 minuti. Scopri che tipo di partner sei davvero e chi è la tua anima affine.',
        pt: '10 momentos de namoro, 2 a 3 minutos. Descubra que tipo de namorado(a) você é de verdade e quem combina com você.',
        ru: '10 ситуаций из отношений, 2–3 минуты. Узнай, какой ты в любви на самом деле и кто тебе подходит больше всех.',
      },
    },
    {
      id: 'nickname',
      emoji: '🏷️',
      category: 'create',
      added: '2026-10-05',
      path: 'https://nickname.example.com/',
      title: { ko: '닉네임 생성기', en: 'Nickname Generator', ja: 'ニックネーム作成', zh: '昵称生成器', fr: 'Générateur de pseudo', de: 'Nickname Generator', th: 'ตั้งชื่อเล่น', vi: 'Tạo nickname', es: 'Generador de apodos', it: 'Generatore di nickname', pt: 'Gerador de nickname', ru: 'Генератор ников' },
      desc: {
        ko: '귀여운·멋진·웃긴·몽환적인 분위기를 고르고 이름을 넣으면 나만의 닉네임이 뚝딱. 마음에 들 때까지 다시 뽑아요.',
        en: 'Pick a vibe, add your name if you like, and get a one-of-a-kind nickname. Spin again until it feels right, then copy it.',
        ja: '雰囲気を選んで名前を入れるだけで、自分だけのニックネームが完成。気に入るまで何度でも作れます。',
        zh: '选一种风格，再输入名字，就能得到专属昵称。不满意可以反复重抽，满意后一键复制。',
        fr: 'Choisis une ambiance, ajoute ton prénom si tu veux et obtiens un pseudo unique. Relance jusqu’à ce qu’il te plaise, puis copie-le.',
        de: 'Stimmung wählen, auf Wunsch den Namen dazugeben und einen einzigartigen Nickname bekommen. Neu würfeln, bis er passt.',
        th: 'เลือกบรรยากาศ ใส่ชื่อของคุณได้ถ้าอยากใส่ แล้วรับชื่อเล่นสุดเก๋ ไม่ถูกใจก็สุ่มใหม่ได้ ก๊อปปี้ใช้ได้ทันที',
        vi: 'Chọn phong cách, thêm tên của bạn nếu muốn và nhận ngay nickname độc đáo. Không ưng thì tạo lại, rồi sao chép.',
        es: 'Elige un estilo, añade tu nombre si quieres y consigue un apodo único. Vuelve a sacar hasta que te guste y cópialo.',
        it: 'Scegli un mood, aggiungi il tuo nome se vuoi e ottieni un nickname unico. Rigenera finché non ti piace, poi copialo.',
        pt: 'Escolha um clima, coloque seu nome se quiser e ganhe um nickname único. Gere de novo até gostar e copie.',
        ru: 'Выбери настроение, добавь своё имя, если хочешь, и получи ник, которого больше ни у кого нет. Не нравится — крути заново и копируй.',
      },
    },
    {
      id: 'coinflip',
      emoji: '🪙',
      category: 'vote',
      added: '2026-10-05',
      path: 'https://coinflip.example.com/',
      title: { ko: '동전 던지기', en: 'Coin Flip', ja: 'コイントス', zh: '抛硬币', fr: 'Pile ou face', de: 'Münzwurf', th: 'โยนเหรียญ', vi: 'Tung đồng xu', es: 'Cara o cruz', it: 'Testa o croce', pt: 'Cara ou coroa', ru: 'Орёл и решка' },
      desc: {
        ko: '앞면이냐 뒷면이냐, 동전을 던져 바로 정해요. 두 선택지 이름을 바꿀 수 있고 주사위도 1~3개 굴릴 수 있어요.',
        en: 'Heads or tails? Flip a coin to decide, name the two sides yourself, or roll one to three dice instead.',
        ja: 'コイントスで表か裏かをすぐ決められます。2つの選択肢の名前も変えられて、サイコロも1〜3個振れます。',
        zh: '正面还是反面，抛一枚硬币马上决定。两面的名字可以自己改，也可以掷1到3个骰子。',
        fr: 'Pile ou face ? Lance la pièce pour trancher, nomme les deux côtés, ou lance de un à trois dés.',
        de: 'Kopf oder Zahl? Münze werfen und entscheiden, beide Seiten selbst benennen oder ein bis drei Würfel rollen.',
        th: 'หัวหรือก้อย โยนเหรียญตัดสินได้ทันที ตั้งชื่อสองด้านเองได้ และทอยลูกเต๋าได้ 1-3 ลูก',
        vi: 'Sấp hay ngửa? Tung đồng xu để quyết định, tự đặt tên hai mặt hoặc gieo từ một đến ba xúc xắc.',
        es: '¿Cara o cruz? Lanza la moneda para decidir, ponle nombre a los dos lados o tira de uno a tres dados.',
        it: 'Testa o croce? Lancia la moneta per decidere, dai un nome ai due lati o tira da uno a tre dadi.',
        pt: 'Cara ou coroa? Jogue a moeda para decidir, dê nome aos dois lados ou role de um a três dados.',
        ru: 'Орёл или решка? Подбрось монетку и реши, назови обе стороны сам или брось от одного до трёх кубиков.',
      },
    },
    {
      id: 'mole',
      emoji: '🔨',
      category: 'game',
      added: '2026-10-06',
      path: 'https://mole.example.com/',
      title: { ko: '두더지 잡기', en: 'Whack-a-Mole', ja: 'もぐらたたき', zh: '打地鼠', fr: 'Jeu de la taupe', de: 'Hau den Maulwurf', th: 'เกมตีตัวตุ่น', vi: 'Game đập chuột chũi', es: 'Golpea al topo', it: 'Colpisci la talpa', pt: 'Jogo da toupeira', ru: 'Бей крота' },
      desc: {
        ko: '구멍에서 튀어나오는 두더지를 톡톡! 폭탄은 피하고 30초 안에 최고 점수에 도전하세요.',
        en: 'Tap the moles as they pop out of the holes, dodge the bombs and beat the clock in 30 seconds.',
        ja: '穴から出てくるもぐらをタップ！爆弾はよけて、30秒でハイスコアを目指そう。',
        zh: '地鼠从洞里冒头就快点一下，遇到炸弹别碰，30秒内冲高分、拿称号。',
        fr: 'Tape les taupes qui sortent des trous, évite les bombes et bats le chrono en 30 secondes.',
        de: 'Tippe die Maulwürfe an, weiche den Bomben aus und hol dir in 30 Sekunden den Highscore.',
        th: 'แตะตัวตุ่นที่โผล่จากรู หลบระเบิด แล้วทำคะแนนสูงสุดให้ได้ใน 30 วินาที',
        vi: 'Chạm chuột chũi thò lên từ các hố, né bom và ghi điểm cao nhất trong 30 giây.',
        es: 'Toca los topos que asoman por los agujeros, esquiva las bombas y bate tu récord en 30 segundos.',
        it: 'Tocca le talpe che spuntano dalle buche, evita le bombe e batti il record in 30 secondi.',
        pt: 'Toque nas toupeiras que saem dos buracos, desvie das bombas e bata o recorde em 30 segundos.',
        ru: 'Тапай по кротам, выскакивающим из нор, обходи бомбы и набери рекорд за 30 секунд.',
      },
    },
    {
      id: 'animal',
      emoji: '🦊',
      category: 'test',
      added: '2026-10-06',
      path: 'https://animal.example.com/',
      title: { ko: '나와 닮은 동물 테스트', en: 'Which Animal Are You?', ja: '動物診断', zh: '你是什么动物测试', fr: 'Quel animal es-tu ?', de: 'Welches Tier bist du?', th: 'ทดสอบสัตว์ที่ใช่คุณ', vi: 'Bạn là con vật nào?', es: '¿Qué animal eres?', it: 'Che animale sei?', pt: 'Que animal você é?', ru: 'Какое ты животное?' },
      desc: {
        ko: '약속 취소, 한밤중 전화, 낯선 파티까지 8가지 순간으로 알아보는 나와 닮은 동물. 2~3분이면 끝나요.',
        en: '8 everyday moments, 2–3 minutes. Find the animal that matches your personality, plus your best match.',
        ja: '予定のドタキャンから真夜中の電話まで、8つの場面で分かるあなたに似た動物。約2〜3分。',
        zh: '从临时放鸽子到半夜来电，8个日常小场景，2~3分钟测出和你最像的动物。',
        fr: '8 petits moments du quotidien, 2 à 3 minutes. Découvre l’animal qui te ressemble, et ton match idéal.',
        de: '8 Alltagsmomente, 2–3 Minuten. Finde das Tier, das zu deiner Persönlichkeit passt – und dein perfektes Match.',
        th: '8 สถานการณ์ในชีวิตประจำวัน ใช้เวลา 2–3 นาที รู้เลยว่าคุณคล้ายสัตว์อะไรที่สุด พร้อมคู่ที่เข้ากัน',
        vi: '8 khoảnh khắc đời thường, 2–3 phút. Tìm con vật giống tính cách bạn nhất và người hợp với bạn nhất.',
        es: '8 momentos cotidianos, 2 o 3 minutos. Descubre qué animal se parece a tu personalidad y con quién haces match.',
        it: '8 momenti quotidiani, 2-3 minuti. Scopri quale animale somiglia alla tua personalità e chi è la tua anima affine.',
        pt: '8 momentos do dia a dia, 2 a 3 minutos. Descubra qual animal combina com sua personalidade e quem é seu par ideal.',
        ru: '8 житейских ситуаций, 2–3 минуты. Узнай, на какое животное ты похож и кто тебе подходит больше всех.',
      },
    },
    {
      id: 'fancytext',
      emoji: '✨',
      category: 'create',
      added: '2026-10-07',
      path: 'https://fancytext.example.com/',
      title: { ko: '글꼴 변환기', en: 'Fancy Text Generator', ja: 'おしゃれ文字変換', zh: '花式字体生成器', fr: 'Générateur de police', de: 'Schriftarten Generator', th: 'แปลงฟอนต์ตัวอักษร', vi: 'Tạo chữ nghệ thuật', es: 'Generador de letras', it: 'Generatore di font', pt: 'Gerador de letras', ru: 'Генератор шрифтов' },
      desc: {
        ko: '글을 입력하면 굵게·필기체·동그라미·거꾸로 등 멋진 글씨체로 바꿔 줘요. 누르면 바로 복사, 한글도 꾸미기 OK.',
        en: 'Type anything and see it in bold, script, bubble, upside-down and more fancy styles. Tap one to copy and paste it anywhere.',
        ja: '文字を入れるだけで、太字・筆記体・丸文字・上下反転などおしゃれな文字に変換。タップでコピー、日本語の飾りも。',
        zh: '输入文字，一键变成粗体、手写体、圆圈字、颠倒等花式字体，点一下即可复制，中文也能加装饰。',
        fr: 'Écris ton texte et vois-le en gras, cursive, bulles, à l’envers et plus. Touche un style pour le copier et le coller partout.',
        de: 'Text eingeben und in Fett, Schreibschrift, Kreisen, kopfüber und mehr sehen. Stil antippen, kopieren und überall einfügen.',
        th: 'พิมพ์ข้อความแล้วดูเป็นตัวหนา ลายมือ วงกลม กลับหัว และอีกหลายสไตล์ แตะเพื่อคัดลอกไปวางได้ทุกที่',
        vi: 'Gõ chữ và xem nó thành chữ đậm, viết tay, bong bóng, lộn ngược và nhiều kiểu khác. Chạm để sao chép rồi dán ở đâu cũng được.',
        es: 'Escribe tu texto y míralo en negrita, cursiva, burbujas, al revés y más. Toca un estilo para copiarlo y pégalo donde quieras.',
        it: 'Scrivi il testo e guardalo in grassetto, corsivo, bolle, capovolto e altro. Tocca uno stile per copiarlo e incollarlo ovunque.',
        pt: 'Digite seu texto e veja em negrito, cursiva, bolhas, de cabeça para baixo e mais. Toque num estilo para copiar e colar onde quiser.',
        ru: 'Введи текст и посмотри его жирным, рукописным, в пузырьках, вверх ногами и не только. Нажми на стиль, скопируй и вставь куда угодно.',
      },
    },
    {
      id: 'lotto',
      emoji: '🎱',
      category: 'vote',
      added: '2026-10-07',
      path: 'https://lotto.example.com/',
      title: { ko: '로또 번호 생성기', en: 'Lotto Number Generator', ja: 'ロト番号ジェネレーター', zh: '彩票号码生成器', fr: 'Générateur de loto', de: 'Lottozahlen-Generator', th: 'สุ่มเลขลอตเตอรี่', vi: 'Tạo số xổ số', es: 'Generador de lotería', it: 'Generatore di lotto', pt: 'Gerador de loteria', ru: 'Генератор лото' },
      desc: {
        ko: '한국 로또 6/45, 유로 방식, 미국 파워볼, 직접 정한 범위까지. 꼭 넣을 번호와 뺄 번호를 정하고 최대 5게임을 공이 굴러 나오는 연출과 함께 뽑아요. 오락용이에요.',
        en: 'Draw lucky numbers for Korea 6/45, a Euro-style game, US Powerball or your own range. Keep or skip numbers, up to five games.',
        ja: '韓国ロト6/45、ユーロ式、米国パワーボール、自由な範囲で番号を引けます。入れる数字と外す数字を決めて、最大5口までボールが転がる演出つき。お楽しみ用です。',
        zh: '韩国乐透6/45、欧洲式、美国强力球或自定义范围，随手摇一组幸运号码。可固定或排除号码，一次最多5注，附彩球滚动动画，仅供娱乐。',
        fr: 'Tire des numéros pour le 6/45 coréen, façon Euro, Powerball US ou ta plage. Fixe ou exclus des numéros, jusqu’à cinq grilles.',
        de: 'Zieh Zahlen für Korea 6/45, Euro-Stil, US-Powerball oder eigenen Bereich. Zahlen behalten oder streichen, bis zu fünf Tipps.',
        th: 'สุ่มเลขนำโชคแบบลอตโต้เกาหลี 6/45 แบบยูโร พาวเวอร์บอลสหรัฐ หรือกำหนดช่วงเอง ล็อกหรือตัดเลขได้ สุ่มได้สูงสุด 5 ชุด เพื่อความสนุกเท่านั้น',
        vi: 'Quay số may mắn kiểu lotto Hàn Quốc 6/45, Euro, Powerball Mỹ hoặc khoảng số tự đặt. Giữ hoặc loại số, tối đa năm bộ. Chỉ để giải trí.',
        es: 'Saca números del 6/45 coreano, estilo Euro, Powerball de EE. UU. o tu rango. Fija o descarta números, hasta cinco apuestas.',
        it: 'Estrai numeri per il 6/45 coreano, stile Euro, Powerball USA o un tuo intervallo. Fissa o escludi numeri, fino a cinque giocate.',
        pt: 'Sorteie números do 6/45 coreano, estilo Euro, Powerball dos EUA ou seu intervalo. Fixe ou exclua números, até cinco jogos.',
        ru: 'Вытяни числа для корейского 6/45, Евролото, Powerball или своего диапазона. Закрепляй и исключай числа, до пяти билетов.',
      },
    },
    {
      id: 'brick',
      emoji: '🧱',
      category: 'game',
      added: '2026-10-08',
      path: 'https://brick.example.com/',
      title: { ko: '벽돌깨기', en: 'Brick Breaker', ja: 'ブロック崩し', zh: '打砖块', fr: 'Casse-briques', de: 'Breakout-Spiel', th: 'เกมตีบล็อก', vi: 'Game phá gạch', es: 'Rompe ladrillos', it: 'Spaccamattoni', pt: 'Quebra-tijolos', ru: 'Арканоид' },
      desc: {
        ko: '패들로 공을 튕겨 알록달록 벽돌을 와르르! 목숨 3개로 몇 단계까지 깰 수 있을까요?',
        en: 'Bounce the ball off your paddle and smash the neon bricks. Three lives, faster stages — how far can you go?',
        ja: 'パドルでボールを打ち返して、カラフルなブロックを崩そう。ライフは3つ、どこまで進める？',
        zh: '用挡板把球弹回去，砸碎一排排霓虹砖块。三条命，关卡越来越快，你能闯几关？',
        fr: 'Renvoie la balle avec ta raquette et casse les briques néon. Trois vies, des niveaux de plus en plus rapides.',
        de: 'Lenk den Ball mit dem Schläger zurück und zerleg die Neon-Steine. Drei Leben, jedes Level etwas schneller.',
        th: 'ใช้ไม้ตีลูกบอลเด้งกลับไปทุบบล็อกสีนีออน มี 3 ชีวิต ด่านยิ่งเร็วขึ้น ไปได้ถึงด่านไหน?',
        vi: 'Đỡ bóng bằng thanh trượt để phá những hàng gạch neon. 3 mạng, màn sau nhanh hơn — bạn đi được bao xa?',
        es: 'Rebota la pelota con tu paleta y rompe los ladrillos neón. Tres vidas y niveles cada vez más rápidos.',
        it: 'Rimanda la palla con la racchetta e distruggi i mattoni al neon. Tre vite, livelli sempre più veloci.',
        pt: 'Rebata a bola com a raquete e quebre os tijolos neon. Três vidas e fases cada vez mais rápidas.',
        ru: 'Отбивай мяч платформой и разбивай неоновые блоки. Три жизни, уровни всё быстрее — как далеко пройдёшь?',
      },
    },
    {
      id: 'mentalage',
      emoji: '🧠',
      category: 'test',
      added: '2026-10-08',
      path: 'https://mentalage.example.com/',
      title: { ko: '정신연령 테스트', en: 'Mental Age Test', ja: '精神年齢診断', zh: '心理年龄测试', fr: 'Test d’âge mental', de: 'Mentales Alter Test', th: 'ทดสอบอายุทางจิตใจ', vi: 'Trắc nghiệm tuổi tâm lý', es: 'Test de edad mental', it: 'Test dell’età mentale', pt: 'Teste de idade mental', ru: 'Психологический возраст' },
      desc: {
        ko: '주말 아침, 단톡방, 비 오는 휴일… 12가지 일상 질문으로 알아보는 내 마음의 나이. 2~3분이면 끝나요.',
        en: '12 light everyday questions, 2–3 minutes. Find out how old your mind really is, down to the number.',
        ja: '週末の朝、グループLINE、雨の休日…12の日常の質問でわかる心の年齢。2〜3分で完了。',
        zh: '周末早晨、群聊、下雨的假日……12道日常小题，2~3分钟测出你的心理年龄。',
        fr: '12 petites questions du quotidien, 2 à 3 minutes. Découvre l’âge réel de ton esprit, au chiffre près.',
        de: '12 leichte Alltagsfragen, 2–3 Minuten. Finde heraus, wie alt dein Kopf wirklich ist – auf das Jahr genau.',
        th: 'คำถามชีวิตประจำวัน 12 ข้อ ใช้เวลา 2–3 นาที รู้เลยว่าใจคุณอายุเท่าไหร่กันแน่',
        vi: '12 câu hỏi đời thường, 2–3 phút. Khám phá tâm hồn bạn thật ra bao nhiêu tuổi.',
        es: '12 preguntas ligeras del día a día, 2 o 3 minutos. Descubre cuántos años tiene de verdad tu mente.',
        it: '12 domande leggere di tutti i giorni, 2-3 minuti. Scopri quanti anni ha davvero la tua testa.',
        pt: '12 perguntas leves do dia a dia, 2 a 3 minutos. Descubra quantos anos sua mente tem de verdade.',
        ru: '12 лёгких житейских вопросов, 2–3 минуты. Узнай, сколько лет на самом деле твоей душе.',
      },
    },
  ],
  // </sites:generated>
};
